
servidor:
 cantidadCli: '2'

users:
 - name: 'martinez'
   password: 'racing'
 - name: 'mascherano'
   password: 'river'
 - name: 'riquelme'
   password: 'boca'
 - name: 'barco'
   password: 'independiente'
 - name: 'salas'
   password: 'allboys'


conexion:
 ip: '192.168.0.9'
 puerto: '8080'